# using modules replaces the need for themes...
#module:
#  imports:
#    - path: github.com/adityatelange/hugo-PaperMod
#    - path: github.com/martignoni/hugo-notice

# https://github.com/adityatelange/hugo-PaperMod/wiki/Variables
baseURL: https://www.jimangel.io/
languageCode: en-us
title: "Jim Angel | jimangel.io"
theme: ["hugo-notice", "PaperMod"]
permalinks:
  posts: /posts/:slug/ # uses title if no slug is provided
# copyright: © 2022 {{ now.Year }} [jimangel.io](https://jimangel.io)

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors:
  - error-remote-getjson

# Ignore the README.md file from being watched for changes
ignoreFiles:
  - "README.md"

staticDir:
  - static
#  - assets

# enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css

minify:
  disableXML: true
  # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          # category: categories
          tag: tags
          # series: series
        menu:
            main:
                - name: Posts
                  url: posts/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 15
                # - name: Series
                #   url: series/
                #   weight: 20
                # - name: About Me
                #   url: /

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: development # netlify.toml sets this to production (HUGO_ENV) to enable google analytics, opengraph, twitter-cards and schema.
  #title: jimangel.io
  description: "A collection of walkthroughs, rants, and hacks on emerging cloud technologies. Jim Angel is an Infrastructure Cloud Consultant at Google"
  # added manually via partials
  # adsense:
  #   client: "ca-pub-8156053398572049"
  #   inArticleSlot: "6076177664"
  # schema for search / SEO
  schema:
    publisherType: Website

  # keywords for homepage SEO
  keywords:
  - blog
  - kubernetes
  - cloud
  - tech
  - jim angel
  - cloud native
  - james angel
  author: Jim Angel
  # author: ["Me", "You"] # multiple authors
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#twitter-cards-support
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  images:
    - /img/social.jpg # This is the root pic when sharing on social media
  label:
    text: jimangel.io # sets the top left blue "home" link text
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light, auto
  disableThemeToggle: false
  disableShare: true
  ShowReadingTime: true
  ShowShareButtons: false
  #ShareButtons:
  #  - twitter
  #  - linkedin
  #  - reddit
  ShowPostNavLinks: true # Show Previous and Next Posts below a Post
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  # ShowFullTextinRSS: false
  ShowRssButtonInSectionTermList: false # don't show RSS on the post link
  UseHugoToc: true
  disableSpecial1stPost: true
  displayFullLangName: true
  disableScrollToTop: true
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets:
    # not needed anymore: https://github.com/adityatelange/hugo-PaperMod/pull/1364
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: false # https://github.com/adityatelange/hugo-PaperMod/issues/89#issuecomment-736549907
    favicon: "/favicon.ico"
    favicon16x16: "/img/favicon-16x16.png"
    favicon32x32: "/img/favicon-32x32.png"
    apple_touch_icon: "/img/apple-touch-icon.png"
    safari_pinned_tab: "/img/safari-pinned-tab.svg"
    # theme_color: "#089de3" for the browser bar color...

  profileMode:
        enabled: true
        title: "Jim Angel" # optional default will be site title
        subtitle: |
           Infrastructure Cloud Consultant at <span style="color:#4285F4">G</span><span style="color:#DB4437">o</span><span style="color:#F4B400">o</span><span style="color:#4285F4">g</span><span style="color:#0F9D58">l</span><span style="color:#DB4437">e</span>

           _Littering the internet with documentation since 2017_
        imageUrl: "/img/me.jpg" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        # buttons:
        #   - name: Blog Archive
        #     url: "/archive"
        #  - name: Github
        #    url: "https://github.com/jimangel"
  socialIcons:
    - name: twitter
      url: "https://twitter.com/JimmAngel"
    - name: github
      url: "https://github.com/jimangel"
    - name: linkedin
      url: "https://www.linkedin.com/in/angeljim/"
    - name: rss
      url: "index.xml"
  cover:
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    responsiveImages: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    #location: 0
    #distance: 0
    ignoreLocation: true
    threshold: 0.0
    minMatchCharLength: 3
    keys: ["content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    # https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
    highlight:
      codeFences: true
      guessSyntax: true
      lineNos: false
      noClasses: false
      style: dracula

privacy:
    vimeo:
        disabled: false
        simple: true
    twitter:
        disabled: false
        enableDNT: true
        simple: true
    instagram:
        disabled: false
        simple: true
    youtube:
        disabled: false
        privacyEnhanced: true


# changes in 1.20
services:
  disqus:
    shortname: jimangel
  googleAnalytics:
    id: G-7X0S9Y56NW # Updated to G4A 8/27/2022
  instagram:
      disableInlineCSS: true
  twitter:
      disableInlineCSS: false