[build]
publish = "public"
command = "hugo --gc"
# removed --minify

[build.environment]
HUGO_VERSION = "0.108.0"
HUGO_ENV = "production"

[build.processing]
# If skip_processing = true, all other settings are ignored
skip_processing = false

[build.processing.css]
bundle = true
minify = false

[build.processing.js]
bundle = false
# not minifying to maintain sha integrity
minify = false

[build.processing.html]
pretty_urls = false

[build.processing.images]
compress = false

# removed content security policy and x from options for G4A
#[[headers]]
#  for = "/*"
#  [headers.values]
#  Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' https:; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://jimangel.disqus.com https://c.disquscdn.com https://*.cloudfront.net https://gist.github.com https://pagead2.googlesyndication.com https://github.githubassets.com https://cdnjs.buymeacoffee.com; prefetch-src 'self' https://c.disquscdn.com https://disqus.com; frame-src 'self' https://disqus.com; style-src-elem 'self' https://c.disquscdn.com 'unsafe-inline' https://github.githubassets.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com"
#  X-Frame-Options = "DENY"
#  X-Content-Type-Options = "nosniff"
#  X-XSS-Protection = "1; mode=block"

# cache images for a week
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"

[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"